### ISSUE TITLE
Change wallet address 

### ISSUE THREAD

**Issue by Kuldipplay** [coinut/api#1]
Respected management, 
I had added bitcoin address but litecoin has been mined. Now I want to change my wallet Crypto Currency address by removing bitcoin address & adding litecoin crypto currency address. Hence, please help me out of the problem. kuldipshil@yahoo.com.  Thank you

**Comment by wangxinxi** [comment]
I don't quite understand your question. Are you saying that you want to remove your Bitcoin address on coinut.com and then add a Litecoin address?

**Comment by raffshedee** [comment]
I want to add bitcoin address on coinut.con and the sametime i want add litecoin address.. 
Please help me...my email.

ravieraclub@gmail.com. tq
