### ISSUE TITLE
nonce

### ISSUE THREAD

**Issue by ghost** [coinut/api#3]
Where do I get the "nonce" number from is this just a random # I choose?

Also is there a websocket call for all crypto/currency pairs on the exchange?

**Comment by countcain** [comment]
@Placid7  https://github.com/coinut/api/wiki/Websocket-API#nonce For nonce, you can choose any number as long as it meets the requirement.

**Comment by countcain** [comment]
@Placid7 You can fetch all pairs' ticks at the same time. The request is 
```js
{"request": "inst_tick", "sec_type": "SPOT",  subscribe: true, "nonce": 391166762}
```
